version: '3'
services:
  gnpsmasscalculator-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnpsmasscalculator-dash
    volumes:
      - ./output:/app/output:rw
      - ./logs:/app/logs:rw
    ports:
    - "6559:5000"
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: gnpsmasscalculator.ucsd.edu
      VIRTUAL_PORT: 6559
      LETSENCRYPT_HOST: gnpsmasscalculator.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu
    restart: on-failure
    command: /app/run_server.sh

networks:
  nginx-net:
    external:
      name: nginx-net